import { useState } from "react";
import { useAuth } from "@/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";

export default function AuthPage() {
  const [mode, setMode] = useState<"login" | "register">("login");
    const [email, setEmail] = useState("");
      const [password, setPassword] = useState("");
        const { login, register, isLoginPending, isRegisterPending } = useAuth();
          const { toast } = useToast();

            const isPending = isLoginPending || isRegisterPending;

              async function handleSubmit(e: React.FormEvent) {
                  e.preventDefault();
                      try {
                            if (mode === "login") {
                                    await login({ email, password });
                                            toast({ title: "Welcome back!" });
                                                  } else {
                                                          await register({ email, password });
                                                                  toast({ title: "Account created!", description: "You're now logged in." });
                                                                        }
                                                                            } catch (err: any) {
                                                                                  toast({
                                                                                          title: mode === "login" ? "Login failed" : "Registration failed",
                                                                                                  description: err?.message ?? "Something went wrong",
                                                                                                          variant: "destructive",
                                                                                                                });
                                                                                                                    }
                                                                                                                      }

                                                                                                                        return (
                                                                                                                            <div className="min-h-screen flex items-center justify-center bg-background p-4">
                                                                                                                                  <Card className="w-full max-w-sm">
                                                                                                                                          <CardHeader className="text-center">
                                                                                                                                                    <div className="flex justify-center mb-2">
                                                                                                                                                                <svg aria-label="Year Ahead" viewBox="0 0 32 32" width="32" height="32" fill="none">
                                                                                                                                                                              <rect x="2" y="6" width="28" height="24" rx="4" stroke="currentColor" strokeWidth="2" />
                                                                                                                                                                                            <path d="M2 12h28" stroke="currentColor" strokeWidth="2" />
                                                                                                                                                                                                          <rect x="8" y="2" width="2" height="6" rx="1" fill="currentColor" />
                                                                                                                                                                                                                        <rect x="22" y="2" width="2" height="6" rx="1" fill="currentColor" />
                                                                                                                                                                                                                                    </svg>
                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                        <CardTitle className="text-xl">Year Ahead</CardTitle>
                                                                                                                                                                                                                                                                  <CardDescription>
                                                                                                                                                                                                                                                                              {mode === "login" ? "Sign in to your account" : "Create a new account"}
                                                                                                                                                                                                                                                                                        </CardDescription>
                                                                                                                                                                                                                                                                                                </CardHeader>
                                                                                                                                                                                                                                                                                                        <CardContent>
                                                                                                                                                                                                                                                                                                                  <form onSubmit={handleSubmit} className="space-y-4">
                                                                                                                                                                                                                                                                                                                              <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                            <Label htmlFor="email">Email</Label>
                                                                                                                                                                                                                                                                                                                                                          <Input
                                                                                                                                                                                                                                                                                                                                                                          id="email"
                                                                                                                                                                                                                                                                                                                                                                                          type="email"
                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="you@example.com"
                                                                                                                                                                                                                                                                                                                                                                                                                          value={email}
                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          autoComplete="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Label htmlFor="password">Password</Label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            id="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder={mode === "register" ? "At least 8 characters" : ""}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            autoComplete={mode === "login" ? "current-password" : "new-password"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            minLength={mode === "register" ? 8 : undefined}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Button type="submit" className="w-full" disabled={isPending}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {isPending ? "Please wait..." : mode === "login" ? "Sign in" : "Create account"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="mt-4 text-center text-sm text-muted-foreground">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {mode === "login" ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <>Don&apos;t have an account?{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={() => setMode("register")} className="underline text-foreground hover:text-primary">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Sign up
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <>Already have an account?{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button onClick={() => setMode("login")} className="underline text-foreground hover:text-primary">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Sign in
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              