import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useAuth } from "@/hooks/useAuth";
import { apiRequest } from "@/lib/queryClient";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";
import { LogOut, User } from "lucide-react";

type Profile = {
  displayName?: string | null;
    bio?: string | null;
      avatarUrl?: string | null;
      };

      export default function ProfilePage() {
        const { user, logout } = useAuth();
          const { toast } = useToast();
            const queryClient = useQueryClient();

              const { data: profile, isLoading } = useQuery<Profile>({
                  queryKey: ["/api/profile"],
                      enabled: !!user,
                        });

                          const [displayName, setDisplayName] = useState("");
                            const [bio, setBio] = useState("");

                              // Sync form state when profile loads
                                const [synced, setSynced] = useState(false);
                                  if (profile && !synced) {
                                      setDisplayName(profile.displayName ?? "");
                                          setBio(profile.bio ?? "");
                                              setSynced(true);
                                                }

                                                  const updateMutation = useMutation({
                                                      mutationFn: async (data: Partial<Profile>) => {
                                                            const res = await apiRequest("PATCH", "/api/profile", data);
                                                                  return res.json();
                                                                      },
                                                                          onSuccess: () => {
                                                                                queryClient.invalidateQueries({ queryKey: ["/api/profile"] });
                                                                                      toast({ title: "Profile updated!" });
                                                                                          },
                                                                                              onError: () => {
                                                                                                    toast({ title: "Failed to update profile", variant: "destructive" });
                                                                                                        },
                                                                                                          });

                                                                                                            async function handleSave(e: React.FormEvent) {
                                                                                                                e.preventDefault();
                                                                                                                    await updateMutation.mutateAsync({ displayName, bio });
                                                                                                                      }

                                                                                                                        async function handleLogout() {
                                                                                                                            await logout();
                                                                                                                              }

                                                                                                                                if (isLoading) {
                                                                                                                                    return <div className="p-6 text-muted-foreground">Loading profile...</div>;
                                                                                                                                      }

                                                                                                                                        return (
                                                                                                                                            <div className="p-6 max-w-xl">
                                                                                                                                                  <div className="flex items-center justify-between mb-6">
                                                                                                                                                          <h1 className="text-2xl font-bold">Profile</h1>
                                                                                                                                                                  <Button variant="outline" size="sm" onClick={handleLogout} className="flex items-center gap-2">
                                                                                                                                                                            <LogOut size={15} />
                                                                                                                                                                                      Sign out
                                                                                                                                                                                              </Button>
                                                                                                                                                                                                    </div>

                                                                                                                                                                                                          <Card className="mb-6">
                                                                                                                                                                                                                  <CardHeader>
                                                                                                                                                                                                                            <div className="flex items-center gap-3">
                                                                                                                                                                                                                                        <div className="w-12 h-12 rounded-full bg-muted flex items-center justify-center">
                                                                                                                                                                                                                                                      <User size={22} className="text-muted-foreground" />
                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                            <CardTitle className="text-base">{user?.email}</CardTitle>
                                                                                                                                                                                                                                                                                                          <CardDescription>Account email</CardDescription>
                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                        </CardHeader>
                                                                                                                                                                                                                                                                                                                                              </Card>

                                                                                                                                                                                                                                                                                                                                                    <Card>
                                                                                                                                                                                                                                                                                                                                                            <CardHeader>
                                                                                                                                                                                                                                                                                                                                                                      <CardTitle>Edit Profile</CardTitle>
                                                                                                                                                                                                                                                                                                                                                                              </CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                      <CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                <form onSubmit={handleSave} className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                            <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                          <Label htmlFor="displayName">Display name</Label>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <Input
                                                                                                                                                                                                                                                                                                                                                                                                                                                        id="displayName"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={displayName}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setDisplayName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="Your name"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Label htmlFor="bio">Bio</Label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          id="bio"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={bio}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setBio(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="A little about you"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          rows={3}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Button type="submit" disabled={updateMutation.isPending}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {updateMutation.isPending ? "Saving..." : "Save changes"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        